### ISSUE TITLE
audience check failed for array type field

### ISSUE THREAD

**Issue by ckukreja** [nginxinc/nginx-openid-connect#10]
With nginx plus openid connect feature, if the id_token has "aud" field of type array (json array object). It fails to validate the token & returns failure.
Error Log: 2019/01/04 19:55:11 [error] 3435#3435: *2 js: OIDC ID Token validation error: missing claim(s) aud

As a workaround, if i disable the audience check from openid_connect.js script everything works fine.

Eg:
"aud": [

    "​https://identity.cloud.com/",
    "e46481793d7744178d5df02d2e7f9a3e"

    ],

Note: Facing this issue with IDCS (https://cloud.oracle.com/idcs)

**Comment by lcrilly** [comment]
This is resolved.
