### ISSUE TITLE
add support to encrypt auth_token cookie

### ISSUE THREAD

**Issue by ckukreja** [nginxinc/nginx-openid-connect#11]
Do we have support for encryption of cookie content & decrypting it back before performing token validation?
The ask is important as with existing infra the cookies are not encrypted & thus this brings in security issues with oauth oidc flows.
By tweaking into the existing code flows, we can do the encrypt/decrypt stuff but raising this question here might get better outcome than doing a tweak. As you have already have had something in your plate or have some dynamic module to serve the purpose.

**Comment by lcrilly** [comment]
Fixed with 9e6ba0c1e26f8454e42a8bbd1afd7250148912c5
