### ISSUE TITLE
add support to set customised headers as response cgi headervar

### ISSUE THREAD

**Issue by ckukreja** [nginxinc/nginx-openid-connect#12]
By this i would like to achieve a use case where customer wants to get couple of attributes values from /userinfo endpoint in form headers. Thus after successful validation, i can set the headers as CGI headervar (not as http header).

**Comment by lcrilly** [comment]
Please contact me at liam@nginx.com so that we can discuss your recent issues.

**Comment by ckukreja** [comment]
> Please contact me at [liam@nginx.com](mailto:liam@nginx.com) so that we can discuss your recent issues.

Hi liam,

I have sent you a mail couple of days back. Whenever you get time kindly go through it once.
Also let me know in case you need further details.

Thanks
