### ISSUE TITLE
nginx-plus-module-njs is not available for Amazon Linux

### ISSUE THREAD

**Issue by hisashiyamaguchi** [nginxinc/nginx-openid-connect#29]
I'm trying to play the OIDC tutorial here, and getting a trouble to install nginx-plus-module-njs on my Amazon Linux instance. Here comes the detail.

$ uname -r
4.14.214-160.339.amzn2.x86_64
$ docker pull nginx:latest
$ docker run --name my-nginx -d -p 8080:80 nginx:latest
$ sudo yum install nginx-plus-module-njs
読み込んだプラグイン:extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                                                    | 3.7 kB  00:00:00
パッケージ nginx-plus-module-njs は利用できません。
エラー: 何もしません

The Japanese log tells "it's unavailable, and nothing has been done."

Any workarounds?

**Comment by lcrilly** [comment]
Hello. This repo is designed to work with NGINX Plus but `docker pull nginx:latest` will obtain NGINX open source. To try this on Amazon Linux use the [marketplace AMI](https://aws.amazon.com/marketplace/pp/B00UU272MM) or a [free trial](https://www.nginx.com/free-trial-request/).
