### ISSUE TITLE
Add support for state parameter

### ISSUE THREAD

**Issue by wkruse** [nginxinc/nginx-openid-connect#3]
There is no support for `state` parameter at the moment to prevent CSRF attacks.

> state 
	RECOMMENDED. Opaque value used to maintain state between the request and the callback. Typically, Cross-Site Request Forgery (CSRF, XSRF) mitigation is done by cryptographically binding the value of this parameter with a browser cookie.
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by lcrilly** [comment]
Not all IdPs send the `state` parameter (it is not mandatory) and our implementation is designed to integrate well with a large number of IdPs. Furthermore, the `nonce` parameter provides the same protection as the`state` parameter and also benefits from being signed by the IdP in the token response. The NGINX Plus OpenID Connect solution verifies the `nonce` value to protect against replay and request forgery attacks.
