### ISSUE TITLE
Add iss claim validation

### ISSUE THREAD

**Issue by wkruse** [nginxinc/nginx-openid-connect#4]
The `iss` (issuer) claim is not validated.

> The Issuer Identifier for the OpenID Provider (which is typically obtained during Discovery) MUST exactly match the value of the iss (issuer) Claim.

http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by lcrilly** [comment]
The NGINX Plus OpenID Connect solution does not perform Discovery, and issuer validation was not implemented, in the interests of configuration simplicity. Audience (`aud`) validation is performed and issuer validation is implicit in the successful signature validation of the ID token.
