### ISSUE TITLE
Add support for aud claim with more than one element 

### ISSUE THREAD

**Issue by wkruse** [nginxinc/nginx-openid-connect#6]
There is no support for `aud` claim with more than one element.

> The Client MUST validate that the `aud` (audience) Claim contains its `client_id` value registered at the Issuer identified by the `iss` (issuer) Claim as an audience. **The `aud` (audience) Claim MAY contain an array with more than one element.** The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client.

http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

**Comment by lcrilly** [comment]
As of now we do not support aud as an array. This will be reviewed if we come across this requirement in the wild.
