### ISSUE TITLE
error log printing variable rather than it's value

### ISSUE THREAD

**Issue by ckukreja** [nginxinc/nginx-openid-connect#9]
If audience validation fails it throws error & dumps it to oidc_error.log as expected. But in error message instead of showing "$oidc_client" value it prints it as such.

openid_connect.js: here if you see the variable is inside the static print value instead of being outside it.
req.error("OIDC ID Token validation error: aud claim (" + req.vari ables.jwt_claim_aud + ") does not match $oidc_client");

It's a cosmetic bug. I have verified this on google cloud nginx plus vm instance (provided by its marketplace).

**Comment by lcrilly** [comment]
Fixed with R18
