### ISSUE TITLE
Broken images in README.md

### ISSUE THREAD

**Issue by fabriziofiorucci** [nginxinc/nginx-openid-connect#94]
These two links are broken:

https://camo.githubusercontent.com/c7f8bb5379fa373558428c221842c8be585049bf9d2599a4b22d4058c76a1979/68747470733a2f2f7777772e6e67696e782e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30342f6469612d4c432d323031382d30332d33302d4f70656e49442d436f6e6e6563742d617574686f72697a6174696f6e2d636f64652d666c6f772d4e47494e582d383030783432362d30332e737667

https://camo.githubusercontent.com/7421851a53096ee6f6c7d52259520d264686a88b7d02c75a7c4e582643b9b700/68747470733a2f2f7777772e6e67696e782e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30342f6469612d4c432d323031382d30332d33302d4f70656e49442d436f6e6e6563742d61757468656e7469636174696f6e2d636f64652d666c6f772d64657461696c65642d383030783834302d30332e737667

**Comment by lcrilly** [comment]
The offending lines are
https://github.com/nginxinc/nginx-openid-connect/blob/main/README.md?plain=1#L9
https://github.com/nginxinc/nginx-openid-connect/blob/main/README.md?plain=1#L22

I have a mermaid diagrams for the images - it might be a better way forwards. Happy to submit a PR from my fork
See https://github.com/lcrilly/nginx-openid-connect/blob/master/README.md

**Comment by route443** [comment]
Hi @lcrilly ,

I've been aware of your fork for some time and was actually curious why this hadn't been suggested earlier! :)
The idea of replacing the current bin images with mermaid diagrams sounds excellent. It wold make maintain the docs easier and ensure that the diagrams are always up-to-date with the source code.
Please feel free to submit a PR from your fork!

**Comment by lcrilly** [comment]
Ha! I just did it to learn Mermaid and then kinda forgot about it. Will submit a PR soon.

**Comment by lcrilly** [comment]
Submitted https://github.com/nginxinc/nginx-openid-connect/pull/95
